# ec2 host/instance name is stored in .kitchen/default-ubuntu-1604.yml
# last_action should probably be set to create in that file.
# here is what the whole file looks like:
# ---
# server_id: i-xxxxxxx
# hostname: 12.34.56.78
# last_action: create
---
driver:
  # name: vagrant
  name: ec2
  aws_ssh_key_id: bioc-default
  region: us-east-1
  require_chef_omnibus: true
  instance_type: t2.large
  security_group_ids: ["sg-308ba149"]
  subnet_id: subnet-d66a05ec
  availability_zone: us-east-1a

transport:
    ssh_key: /Users/dtenenba/.ec2/bioc-default.pem
    username: ubuntu

provisioner:
  name: chef_zero
  client_rb:
      audit_mode: :enabled
  data_path: test/shared
  data_bags_path: ./test/data_bags
  encrypted_data_bag_secret_key_path: ./secret_for_testing_only


# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
# - name: ubuntu-14.04
 - name: ubuntu-16.04
   driver:
      image_id: ami-c8c6d9a2

suites:
  - name: default
    run_list:
      - role[bbs_devel_linux]
    #   - recipe[BBS-provision-cookbook::default]
