---
driver:
  name: vagrant

provisioner:
  #name: chef_solo
  name: chef_zero
  client_rb:
      audit_mode: :enabled
  data_path: test/shared

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[BBS-provision-cookbook::default]
    attributes:
      bioc_version: "3.3"
      r_version: "3.3"
      use_r_devel: false
      hostname:
          bioc_devel_builder: linux1.bioconductor.org
          bioc_release_builder: linux2.bioconductor.org
