name 'BBS-provision-cookbook'
maintainer 'Andrzej Oles'
maintainer_email 'aoles@embl.de'
license 'Artistic 2.0'
description 'Installs Bioconductor System Dependencies'
long_description 'Installs Bioconductor System Dependencies'
version '0.1.27'
depends 'apt'
depends 'cron'
